<?php
// $Id: allperms.module,v 1.2 2010/05/03 00:38:06 cafuego Exp $

/**
 * Implementation of hook_menu()
 *
 * If admin_menu is installed, having roles expand under
 * the User » Permissions menu is actually really nice.
 */
function allperms_menu() {
  if (!module_exists('admin_menu'))
    return array();

  $items = array();
  foreach (user_roles() as $rid => $role) {
    $items['admin/user/permissions/role/' . $rid] = array(
      'title' => $role,
      'description' => 'Determine access to features by selecting permissions for ' . $role . '.',
      'page callback' => 'allperms_user_admin_perm_redir',
      'page arguments' => array(4),
      'access callback' => 'user_access',
      'access arguments' => array('administer permissions'),
    );
  }
  return $items;
}

/**
 * Helper to redirect the user to the correct role based
 * permissions admin page.
 */
function allperms_user_admin_perm_redir($rid) {
  drupal_goto('admin/user/permissions/'. $rid);
}

function allperms_insert_anchors($element) {
  $element['#prefix'] = '<a href="#' . $element['#value'] . '"></a>';
  return($element);
}

/**
 * Implementation of hook_form_form-id_alter()
 *
 * Insert a `check all' checkbox on top of each role column.
 * Add a javascript snippet for each role, so the checkbox
 * we add can do its thing.
 */
function allperms_form_user_admin_perm_alter(&$form, &$form_state) {

  foreach ($form['role_names'] as $num => $role) {

    // Add a control checkbox for this role.
    $control  = '<label class="option" for="select-all-' . $num . '">';
    $control .= t('Select All');
    $control .= '<br /><input type="checkbox" name="' . $num . '[select all]" id="select-all-' . $num . '" value="select all" class="form-checkbox" />';
    $control .= '</label><br />';

    // Stick the checkbox on top of the role name.
    $form['role_names'][$num]['#value'] = $control . $form['role_names'][$num]['#value'];

    // Generate the javascript to iterate over the checkboxes that apply
    // only to this role and turn them all on or off.
    $js = "$(document).ready(function(){
  var match = 'edit-' + " . $num ." + '-';
  $('#select-all-" . $num . "').click(function(){
    if( $(this).attr('checked')) {
      $('input:checkbox').each(function() {
        if ( $(this).attr('id').substring(0,match.length).match('edit-" . $num . "-') ) {
          $(this).attr('checked', true);
        } else {
        }
      });
    } else {
      $('input:checkbox').each(function() {
        if ( $(this).attr('id').substring(0,match.length).match('edit-" . $num . "-') ) {
          $(this).attr('checked', false);
        }
      });
    }
  });
});";

    drupal_add_js($js, 'inline');
  }

  // Our validation handler MUST run first, so the 'select all' checkbox can be removed
  // to stop the actual form handler from whining.
  $form['#validate'] = is_array($form['#validate']) ? $form['#validate'] : array();
  array_unshift($form['#validate'], 'allperms_form_user_admin_perm_validate');
}

/**
 * Helper for the validation handler.
 */
function allperms_form_user_admin_perm_validate($form, &$form_state) {
  dpm($form_state);
  foreach ($form['role_names'] as $num => $role) {
    unset($form_state['values'][$num . '[select all]']);
  }
}
